### ISSUE TITLE
Error on onclick of components

### ISSUE THREAD

**Issue by vsmarimuthu** [stomita/lwc-dynamic-element#2]
@stomita 
Hi,

I am just rendering a input like this 
`
addFeild() {     
        const node = this.createNode('lightning-input', {
            label: 'Program',
            name: 'Program',
            type:'text',
            maxlength:'80',
            value:'Program',
            placeholder:'Enter Program'
          });
         node.attrs.onclick = this.lightningInputClick.bind();
        const container = this.getActiveContainer();
        container.children.push(node);
    }
    lightningInputClick(key) {
        console.log('Button Clicked');       
    }
`

and HTML is

`<template>
  <c-dynamic-element
    tag={rootNode.tag}
    attrs={rootNode.attrs}
    children={rootNode.children}
  ></c-dynamic-element>
  <div>
    <button onclick={addFeild}>Add Icon</button>   
  </div>
</template>`

But i am getting following error. Can you please help
![image](https://user-images.githubusercontent.com/22540745/95657306-6b834480-0b31-11eb-8df6-18daf1db4ced.png)

 Code image for better clarity

![image](https://user-images.githubusercontent.com/22540745/95657227-f0219300-0b30-11eb-8863-42d213ccbfb2.png)

![image](https://user-images.githubusercontent.com/22540745/95657239-0c253480-0b31-11eb-8042-548af0459590.png)

**Comment by stomita** [comment]
How about changing
```
this.lightningInputClick.bind(this)
```
